units_type: character
feature_source: kaldi
feature_type: fbank
data:
    name: aishell
    vocab: data/aishell/vocab
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: True
    max_input_length: 1500
    max_target_length: 50
    train:
        batch_size: 4
        arkscp: /data1/tianzhengkun/kaldi/egs/aishell/s5/data/train/feats.scp
        text: /data1/tianzhengkun/kaldi/egs/aishell/s5/data/train/character
        cmvnscp: /data1/tianzhengkun/kaldi/egs/aishell/s5/data/train/cmvn.scp
    dev:
        batch_size: 4
        arkscp: /data1/tianzhengkun/kaldi/egs/aishell/s5/data/dev/feats.scp
        text: /data1/tianzhengkun/kaldi/egs/aishell/s5/data/dev/character
        cmvnscp: /data1/tianzhengkun/kaldi/egs/aishell/s5/data/dev/cmvn.scp
model:
    vocab_size: 4337
    feature_dim: 320
    max_input_length: 600
    max_target_length: 50
    d_model: 512
    n_heads: 4
    d_k: 128
    d_v: 128
    d_inner_hid: 1024
    num_enc_layer: 6
    num_dec_layer: 6
    dropout: 0.2
    share_embedding: False
training:
    seed: 2018
    use_gpu: True
    num_gpu: 1
    gpu_ids: 0
    epoches: 30
    label_smoothing: False
    visualization: True
    show_interval: 10
    save_model: exp/transformer
    dev_on_training: False
optimizer:
    n_warmup_steps: 12000
decode:
    beach_size: 10
    beam_width: 10
    n_best: 1
