units_type: character
feature_source: kaldi
feature_type: fbank
data:
    vocab: /tests/vocab
    batch_size: 64
model:
    vocab_size: 30
    feature_dim: 30
    max_inputs_length: 20
    max_target_length: 20
    d_model: 64
    n_heads: 2
    d_k: 32
    d_v: 32
    d_inner_hid: 128
    num_enc_layer: 6
    num_dec_layer: 6
    emb_scale: 1
    dropout: 0.2
    share_embedding: False
training:
    seed: 2018
    use_gpu: False
    num_gpu: 1
    gpu_ids: 0
    epoches: 1
    label_smoothing: False
    visualization: True
    show_interval: 10
    save_model: exp/transformer
    dev_on_training: False
optimizer:
    n_warmup_steps: 4000
decode:
    beach_size: 10
    beam_width: 10
    n_best: 1
